-- MySQL
DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS contact CASCADE;

CREATE TABLE IF NOT EXISTS address (
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   city VARCHAR (255) NOT NULL,
   street_name VARCHAR (255),
   street_type VARCHAR (255),
   number INT,
   permanent boolean,
   personid INT
);
CREATE TABLE IF NOT EXISTS contact (
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   email VARCHAR (255) UNIQUE NOT NULL,
   tel INT NOT NULL
);
CREATE TABLE IF NOT EXISTS person (
   id INTEGER AUTO_INCREMENT PRIMARY KEY,
   lastname VARCHAR (255) NOT NULL,
   firstname VARCHAR (255) NOT NULL,
   contactid INT
);
